### ISSUE TITLE
Multiple groups with multiple footers

### ISSUE THREAD

**Issue by b2dac** [openpsa/grid.js#86] opened 2015-01-27 04:09 UTC
Multiple sub groups of a master group cause the master group footer to only show if the last sub group is expanded. The group footer should not be a part of the last child.

**Comment by OlegKi** [comment] 2015-01-27 11:26
Hi @b2dac !

The described problem is the old bug in jqGrid. You can verify on [the demo](http://www.ok-soft-gmbh.com/jqGrid/grouping2-46.htm) that it exists in jqGrid 4.6 and on [the demo](http://www.ok-soft-gmbh.com/jqGrid/grouping2-47.htm) that it exists in jqGrid 4.7.

Nevertheless it's a bug and every bug should be fixed. I fixed in in [my jqGrid fork](https://github.com/OlegKi/jqGrid). See [the demo](http://www.ok-soft-gmbh.com/jqGrid/OK/grouping2.htm) which uses the fixed code. If you will find the bug in the code please post the issue to [my repository](https://github.com/OlegKi/jqGrid).

You can consider whether the usage of `showSummaryOnHide: true` property of `groupingView` displays more information which you need. See [the next demo](http://www.ok-soft-gmbh.com/jqGrid/OK/grouping2_.htm). It display summary row below of the row with grouping header of the collapsed groups. In any way the choice of `showSummaryOnHide: true` property is independent from the reported issue.

**Comment by meh-uk** [comment] 2015-01-27 12:09
@olegki if you can't work with us then trying to get people to use your code from our repository isn't really acceptable.

**Comment by OlegKi** [comment] 2015-01-27 12:54
Sorry @meh-uk  , but I can't follow your logic. @b2dac wrote about the problem with summary (footer) of grouping. I answered him that it's not a bug which is specific for *your fork*. It's common problem in jqGrid. You didn't made any changes in jqGrid code, which follows the problem.

Moreover I'm trying to fix all bugs in jqGrid, which I find, and to share the solutions with other users of jqGrid. Do you have problem with it? Do you want to provide your own bug fix of the problem or you want to continue applying my fixes in your repository?

The most pity is that you didn't posted any answer to @b2dac . Do you plan to write your own answer to him?

**Comment by bouks** [comment] 2015-01-27 13:26
I think, @OlegKi, that what disturb @meh-uk is you wrote : "I fixed it in my jqGrid fork" but you don't point the fix so we can fix it in this project.
So, if you come in THIS project issues, anwsering only your project is fixed and invite people to yours, sure it is not acceptable.

**Comment by b2dac** [comment] 2015-01-27 14:44
I was unaware of @OlegKi fork. That being said I am grateful that he told me about it. It's nice to have options.

**Comment by b2dac** [comment] 2015-01-27 14:45
I will leave this open so maybe it can get fixed.

**Comment by flack** [comment] 2015-01-27 14:46
Thanks! We will merge Oleg's fix shortly (we have to do some testing before since our codebases are not identical)

**Comment by b2dac** [comment] 2015-01-27 15:18
okay, thank you.

**Closed** 2015-01-27 18:39 UTC

**Comment by b2dac** [comment] 2015-01-28 14:35
Thanks for fixing this. I'm still not sure which repo to go with, yours or @OlegKi . It's too bad you both can't merge the two.

**Comment by meh-uk** [comment] 2015-01-28 14:42
That would be nice :(.

**Comment by flack** [comment] 2015-01-28 14:47
Oh believe me, we've tried for weeks. We've changed things on Oleg's request, discussed for hours on end, we've offered compromises on the things he didn't like, and even merged about 100 of his commits to make it easy for him to switch. But no such luck, all we got out of it were a string of merge errors that we're currently working through...
